### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by EmadAboEsmail** [03stevensmi/Gnome3-Ubuntu-Android-Termux-Test#2]
![Screenshot_2020-06-06-23-13-33-17](https://user-images.githubusercontent.com/46620791/83954680-955af080-a84b-11ea-8337-962084c0b69b.jpg)

**Comment by EmadAboEsmail** [comment]
![Screenshot_2020-06-06-23-20-43-40](https://user-images.githubusercontent.com/46620791/83954793-9c363300-a84c-11ea-990d-c178a0639f3c.jpg)

**Comment by devlocalhost** [comment]
I'm getting the same errors too (mi a3, android 11 custom rom, paranoid android)

**Comment by 03stevensmi** [comment]
Sorry guys but I'm not working on this anymore.
Couldn't get it to properly work myself. I managed to get some of the gui showing but not the
full lot. I gave up on this at that point.

Maybe someone else could try and get gnome running,
But as for me, I gave up on this a while back.

Sorry guys.
